[package]
name = "bojo-quotes-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.10"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rand = "0.8.4"
rocket_cors = "0.5.1"

[dependencies.rocket_contrib]
version = "0.4.10"
default-features = false
features = ["json"]